name: socket_io
description: Dartlang port of socket.io
version: 0.9.0+2
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stream: any
  socket_io_common: any
  uuid: any
dev_dependencies:
  test: ">=1.3.0 <2.0.0"
