name: socket_io
description: Dartlang port of socket.io
version: 0.9.0
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  stream: ^2.1.0
  uuid: "1.0.3"
dev_dependencies:
  test: ">=1.3.0 <2.0.0"
